name: Build & Cache flake outputs

on: push
permissions:
  contents: read
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-cache:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: wimpysworld/nothing-but-nix@main
        with:
          root-safe-haven: "8192"
          mnt-safe-haven: "4096"

      - uses: actions/cache@v4
        with:
          path: |
            /nix/store
            ${{ env.HOME }}/.cache/nix
          key: ${{ runner.os }}-nix-${{ hashFiles('flake.lock') }}
          restore-keys: ${{ runner.os }}-nix-

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true

      - uses: cachix/cachix-action@v15
        with:
          name: supa

      - name: Build flake outputs
        run: |
          nix run nixpkgs#omnix -- ci run \
            --results=$HOME/omci.json

      - name: Push to Cachix
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          nix run github:juspay/cachix-push -- \
            --subflake root \
            --prefix "${BRANCH_NAME}" \
            --cache supa \
            < $HOME/omci.json
