name: Build & Cache flake outputs

on: push

jobs:
  build-and-cache:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: wimpysworld/nothing-but-nix@main

      - name: Set up Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Install Omnix and Cachix
        run: nix --accept-flake-config profile add github:juspay/omnix github:cachix/cachix/latest

      - name: Build flake outputs
        run: om ci run -- --accept-flake-config

      - name: Push to Cachix
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        run: cachix push supa ./result
